oneup_flysystem:
    adapters:
        courses.adapter:
            local:
                directory: '%kernel.project_dir%/app/courses'

#        s3.adapter:
#              awss3v3:
#                  client: s3_client # add service "s3_client"
#                  bucket: ~
#                  prefix: ~

    filesystems:
        courses:
            adapter: courses.adapter
            cache: ~
            alias: ~
            mount: ~