imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: services.yml }

#    - { resource: @ChamiloCoreBundle/Resources/config/admin.yml }
#    - { resource: @ChamiloNotebookBundle/Resources/config/admin.yml }

    # Mopa Bootstrap
    - { resource: mopa/mopa_bootstrap.yml }

    # FriendOfSymfony Bundles
    #- { resource: fos/fos_comment.yml }
    - { resource: fos/fos_rest.yml }

    - { resource: fos/fos_user.yml }
    #- { resource: fos/fos_elastica.yml }
#    - { resource: fos/fos_message.yml }


#    - { resource: @CmfBlogBundle/Resources/config/cmf_routing_auto.xml }
#    - { resource: @CmfBlogBundle/Resources/config/admin.yml }

    - { resource: ivory_ckeditor.yml }

# Sylius
#    - { resource: sylius.yml }

#sylius_resource:
#    resources:
#        app.settings:
#            classes:
#                model: Chamilo\CoreBundle\Entity\SettingsCurrent

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

#theodo_evolution_session:
#    bag_manager_service: theodo_evolution.session.symfony1.bag_manager
#    bag_configuration_service: theodo_evolution.session.symfony1.bag_manager_configuration

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Grid default template
#apy_data_grid:
#    theme: ChamiloCoreBundle::grid.html.twig
#


liip_theme:
    themes: ['web', 'tablet', 'phone']
    active_theme: 'web'
    assetic_integration: true



#jms_translation:
#    configs:
#        app:
#            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
#            output_dir: %kernel.root_dir%/Resources/translations
#            ignored_domains: [routes]
#            excluded_names: ["*TestCase.php", "*Test.php"]
#            excluded_dirs: [cache, data, logs]
##            extractors: [alias_of_the_extractor]

fm_elfinder:
    assets_path: /chamilo_master/web/assets
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
#                    uploads:
#                        show_hidden: false # defaults to false
#                        driver: LocalFileSystem
#                        path: uploads
#                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
#                        upload_deny: ['all']
#                        upload_max_size: 2M
                    local:
                        driver: Flysystem
                        path: uploads
                        flysystem:
                            type: local
                            options:
                              local:
                                  path: %kernel.root_dir%/../web/media/
                        upload_allow: ['all']
                        #upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        #upload_deny: ['all']
                        upload_max_size: 2M

#lunetics_locale:
#    guessing_order:
#        - query
#        - router
#        - session
#        #- browser
#    allowed_locales: "%locales%"


#gregwar_captcha:

# Doctrine audit
sonata_doctrine_orm_admin:
    audit:
        force: false # Audits are set in the admin.yml files with audit:true
