# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    password_encryption: sha1
    locale: 'en'
    url_append: ''
    course_info_is_not_editable: false
    sonata_media.cdn.host: /uploads/media
    sonata_page.varnish.command: 'if [ ! -r "/etc/varnish/secret" ]; then echo "VALID ERROR :/"; else varnishadm -S /etc/varnish/secret -T 127.0.0.1:6082 {{ COMMAND }} "{{ EXPRESSION }}"; fi;'
    locales:
        - en
        - fr
        - es
        - de
    twig.form.resources: ['bootstrap_3_layout.html.twig']


services:
