chamilo_install_flow:
    path: /install
    defaults: { _controller: sylius.controller.process:startAction, scenarioAlias: 'chamilo_install' }

chamilo_upgrade_flow:
    path: /upgrade
    defaults: { _controller: sylius.controller.process:startAction, scenarioAlias: 'chamilo_upgrade' }

chamilo_install_flow_bundle:
    resource: '@SyliusFlowBundle/Resources/config/routing.yml'
    prefix: /install

